// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZj6WWWs3-w0dLxDb4Zz92fm8ailtbzrw',
    appId: '1:641561213971:web:081a73ed315cb91b6b13e6',
    messagingSenderId: '641561213971',
    projectId: 'face-recognition-3c11e',
    authDomain: 'face-recognition-3c11e.firebaseapp.com',
    databaseURL: 'https://face-recognition-3c11e-default-rtdb.firebaseio.com',
    storageBucket: 'face-recognition-3c11e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXpzIoT3bR2Xsy7ZT2sALw--oFpwR-bwU',
    appId: '1:641561213971:android:dc8841641d58a9ae6b13e6',
    messagingSenderId: '641561213971',
    projectId: 'face-recognition-3c11e',
    databaseURL: 'https://face-recognition-3c11e-default-rtdb.firebaseio.com',
    storageBucket: 'face-recognition-3c11e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhmXqIyYsSQlmgcxAqV-x4_FNNTrKPYCU',
    appId: '1:641561213971:ios:aad7f0fc3ce51f0f6b13e6',
    messagingSenderId: '641561213971',
    projectId: 'face-recognition-3c11e',
    databaseURL: 'https://face-recognition-3c11e-default-rtdb.firebaseio.com',
    storageBucket: 'face-recognition-3c11e.appspot.com',
    iosClientId: '641561213971-aq7udubm48l1ka3o77jav88st6g77flu.apps.googleusercontent.com',
    iosBundleId: 'com.flutterflow.facerecognition2',
  );
}
